* jsGuardian
A content filter for websites, emulating dansguardian's score-based filter.
* Deployed at
  - Firefox: https://addons.mozilla.org/en-US/firefox/addon/jsguardian/, and
  - Google Chrome: https://chrome.google.com/webstore/detail/jsguardian/ojofglimbmclnbinpbjnhcmkmipplibi
* Versions
** 0.9.1
*** Added
    Limit option
** 0.9.0
*** Fixed
    back button overrode block page
*** Added
    Whitelist option
** 0.8.1
*** Fixed
    zip/xpi lacked icon file
** 0.8.0
*** Changed
    name (from Score-based web filter) to jsGuardian
** 0.7.0
*** Changed
    webextension (only chromium)
*** Deleted
    safe search (use separate safe search addon for this)
** 0.6.2
*** Added
    Lacked toggle to turn safe search on/off
** 0.6.1
*** Added
   lacked (moderate) safe search on youtube
** 0.5.12
*** Added
   lacked safe search (google, yahoo, bing, ddg)
** 0.4.0
*** Added
   previous versions lacked whitelist
** 0.3.4
*** Fixed
   multiprocess as permission ... ;-)
** 0.3.3
*** reviewer feedback
    multiprocess spelling
    had .gitignore
** 0.3.2
*** Added
   ?: multi-process was not enabled
   default was at 60, which is for small children, now it's at 160
** 0.3.1
*** Fixed
   Bug: counted different cases differently
** 0.3.0
*** Added
   Doc: did not copy dg appropriate values for age groups
** 0.2.2
*** Fixed
    did not find multi-line matches
** 0.2.1
*** Fixed
    old mods were not destroyed on re-setting limit.
** 0.2.0
*** Added
    quotes surrounding single matches
** 0.1.6
*** Fixed
Changing score did not affect anything.
** 0.1.5
*** Fixed
Sites like google with many =<script>= tags made loading very slow.
** 0.1.2
*** Fixed
Was not installable on recent android firefox (45).
** 0.1.1
*** Added
Previous version used innerHTML.
** 0.1.0
*** Added
Had no message which parts triggered filter if blocked.
* Uses Icons
  - filter: https://www.iconfinder.com/icons/383135/filter_icon#size=128
  - flower: https://www.iconfinder.com/icons/3495/flower_icq_icon#size=128
  - bomb: https://www.iconfinder.com/icons/1232/bomb_explosive_icon#size=128
