* JSGuardian: Filter Within Your Browser
A content filter for websites, emulating dansguardian's score-based filter in JavaScript.

[[https://addons.mozilla.org/de/firefox/addon/jsguardian/][https://img.shields.io/amo/v/jsguardian.svg]] 
[[https://addons.mozilla.org/de/firefox/addon/jsguardian/][https://img.shields.io/amo/d/jsguardian.svg]]
[[https://chrome.google.com/webstore/detail/jsguardian/ojofglimbmclnbinpbjnhcmkmipplibi][https://img.shields.io/chrome-web-store/v/ojofglimbmclnbinpbjnhcmkmipplibi.svg]]
* Versions
** 1.5.5
*** Failed to display the correct score
** 1.5.2
*** Failed
    if it was triggered multiple times, the blockpage was shown
** 1.5.1
*** Failed
    by scanning the blockpage, which contained all the words, triggering on that, so that just the cached block page was shown.
** 1.5.0
*** Lacked
    searching of iframes, e.g. in Google Translate
** 1.4.2
*** Failed
    to show the score if an ampersand, =&=, was in the blocked phrases
** 1.4.1
*** Failed
    to persist the blockpage, credits to hllwdfr@github
** 1.4.0
*** Lacked
    speed: Was perceived as too slow to block, due to when the script loaded, and when it showed the block page.
** 1.3.1
*** Failed
    - to load the blockpage in all cases
    - to save/not save and load undefined/empty values
** 1.3.0
*** Lacked
    possibility to set another block page target (like =about:blank=)

    - This needs to be a valid URL. You have been warned (\trade \smiley).
** 1.2.0
*** Lacked
    block reasons were not shown
** 1.1.0
*** Lacked
    refactoring: settings object was in main code file
** 1.0.1
*** Did
    - break on FF Android due to missing application ID
** 1.0.0
*** Lacked
    - block cache + test
*** Did
    - set the block page multiple times
** 0.13.4
*** Lacked
    - test for preset file loading
*** Was
    - less refactored
** 0.13.3
*** Lacked
    - tests
*** Was
    - less refactored
** 0.13.2
*** Fixed
    - logo needs to be IMG
    - capitalization like JSDoc
** 0.13.1
*** Fixed
    - popup.html seems to be blocked on Windows 10.
    - Had layout in HTML.
    - HTML was invalid
** 0.13.0
*** Added
    Popup lacked link to options.
** 0.12.0
*** Added
    managed storage for chrome
*** Fixed
    settings seem to not have worked on windows
** 0.11.0
*** Fixed
    Had settings object hardcoded in main background script, which was not needed if in storage. (Request by Mozilla review)
** 0.10.0
*** Added
    WebExt lacked access to words for scoring.
** 0.9.1
*** Added
    Limit option
** 0.9.0
*** Fixed
    back button overrode block page
*** Added
    Whitelist option
** 0.8.1
*** Fixed
    zip/xpi lacked icon file
** 0.8.0
*** Changed
    name (from Score-based web filter) to jsGuardian
** 0.7.0
*** Changed
    webextension (only chromium)
*** Deleted
    safe search (use separate safe search addon for this)
** 0.6.2
*** Added
    Lacked toggle to turn safe search on/off
** 0.6.1
*** Added
   lacked (moderate) safe search on youtube
** 0.5.12
*** Added
   lacked safe search (google, yahoo, bing, ddg)
** 0.4.0
*** Added
   previous versions lacked whitelist
** 0.3.4
*** Fixed
   multiprocess as permission ... ;-)
** 0.3.3
*** reviewer feedback
    multiprocess spelling
    had .gitignore
** 0.3.2
*** Added
   ?: multi-process was not enabled
   default was at 60, which is for small children, now it's at 160
** 0.3.1
*** Fixed
   Bug: counted different cases differently
** 0.3.0
*** Added
   Doc: did not copy dg appropriate values for age groups
** 0.2.2
*** Fixed
    did not find multi-line matches
** 0.2.1
*** Fixed
    old mods were not destroyed on re-setting limit.
** 0.2.0
*** Added
    quotes surrounding single matches
** 0.1.6
*** Fixed
Changing score did not affect anything.
** 0.1.5
*** Fixed
Sites like google with many =<script>= tags made loading very slow.
** 0.1.2
*** Fixed
Was not installable on recent android firefox (45).
** 0.1.1
*** Added
Previous version used innerHTML.
** 0.1.0
*** Added
Had no message which parts triggered filter if blocked.
* Uses Icons
  - filter: https://www.iconfinder.com/icons/383135/filter_icon#size=128
  - flower: https://www.iconfinder.com/icons/3495/flower_icq_icon#size=128
  - bomb: https://www.iconfinder.com/icons/1232/bomb_explosive_icon#size=128
